// Downloads the OFL-licensed webfonts once and writes assets/fonts.css with
// every face embedded as a data URI. Run once; after that the site needs no
// network at all for type.
//
//   node tools/fetch-fonts.mjs

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = resolve(root, "assets", "fonts.css");

// A modern UA is what makes Google serve woff2 + per-script subsets
// instead of one enormous ttf.
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
           "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const FAMILIES = [
  "Amiri:wght@400",                  // Arabic naskh — the Qur'anic line, headings
  "Cairo:wght@400;600",              // Arabic body / UI
  "Cormorant+Garamond:wght@400;600"  // Latin display
];

// Arabic and basic Latin only — nothing on this page uses latin-ext, and
// dropping it saves well over 100 KB.
const KEEP = new Set(["arabic", "latin"]);

const url = "https://fonts.googleapis.com/css2?" +
  FAMILIES.map(f => `family=${f}`).join("&") + "&display=swap";

const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

// Google labels each block with a /* subset */ comment on the line above.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)];
if (!blocks.length) throw new Error("Could not parse the font CSS — did the UA get rejected?");

const out = [
  "/* Generated by tools/fetch-fonts.mjs — do not edit by hand.",
  "   Amiri, Cairo and Cormorant Garamond are licensed under the SIL Open",
  "   Font License 1.1, which permits embedding. */",
  ""
];

let kept = 0, bytes = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;

  const src = block.match(/url\((https:\/\/[^)]+)\)/);
  if (!src) continue;

  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? "?";
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";

  const buf = Buffer.from(await (await fetch(src[1], { headers: { "User-Agent": UA } })).arrayBuffer());
  bytes += buf.length;
  kept++;

  const fmt = src[1].endsWith(".woff2") ? "woff2" : "truetype";
  const mime = fmt === "woff2" ? "font/woff2" : "font/ttf";

  out.push(
    block
      .replace(/url\(https:\/\/[^)]+\)\s*format\('[^']+'\)/,
               `url(data:${mime};base64,${buf.toString("base64")}) format('${fmt}')`)
      .replace(/@font-face\s*\{/, `@font-face {\n  /* ${family} ${weight} · ${subset} */`)
  );
  out.push("");

  console.log(`  ${family.padEnd(20)} ${weight}  ${subset.padEnd(10)} ${Math.round(buf.length / 1024)} KB`);
}

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, out.join("\n"), "utf8");
console.log(`\n  ${kept} faces -> assets/fonts.css (${Math.round(bytes / 1024)} KB of font data)`);
